services:
  frontend:
    build:
      context: .
      args:
        # Gunakan HTTP jika belum ada SSL, atau HTTPS jika sudah ada SSL
        - VITE_API_URL=https://event.coconut.or.id/api
    container_name: coconut-frontend
    ports:
      - "5173:80"  # Mengarahkan port 5173 VPS ke port 80 di dalam Nginx Docker
    restart: always