services:
  frontend:
    build: .
    container_name: coconut-frontend
    ports:
      - "5173:8080"
    environment:
      # Variabel ini akan ditangkap oleh Vite
      - VITE_API_URL=http://192.168.1.52:8081
    volumes:
      # Sinkronisasi kode agar fitur "Hot Reload" Vite tetap jalan
      - .:/app
      # Mencegah node_modules di komputermu menimpa yang ada di dalam Docker
      - /app/node_modules
    restart: always