frontend:
  build: .
  container_name: coconut-frontend
  ports:
    - "5173:5173"   # Sama di host dan container
  environment:
    - VITE_API_URL=http://192.168.1.52:8081
  volumes:
    - .:/app
    - /app/node_modules
  command: npm run dev -- --host 0.0.0.0 --port 5173
  restart: always
